stages:
  - deploy

variables:
  GIT_STRATEGY: clone

deploy_job:
  stage: deploy
  tags:
    - windows   # ✅ force Windows runner

  script:
    - echo "🚀 Starting deployment"

    - powershell -Command "hostname"
    - powershell -Command "Get-PSDrive"

    - powershell -Command "Remove-Item 'D:\test\output\*' -Recurse -Force -ErrorAction SilentlyContinue"

    - powershell -Command "Copy-Item * -Destination 'D:\test\output' -Recurse -Force"

    - powershell -Command "Get-Content 'D:\test\output\app.py'""
