stages:
  - build
  - deploy

# 🔹 BUILD STAGE (Pull latest GitHub code)
build_job:
  stage: build
  tags:
    - linux

  script:
    - echo "📥 Cleaning old workspace"
    - rm -rf *

    - echo "📥 Cloning latest code from GitHub"
    - git clone https://github.com/kaithareddy03/python-deploy.git .

    - echo "🔍 Checking latest commit"
    - git log -1

    - echo "🔍 Checking branch"
    - git branch

    - echo "📂 Files in repo"
    - ls -l

  artifacts:
    paths:
      - .
    expire_in: 1 hour


# 🔹 DEPLOY STAGE (Windows Server)
deploy_job:
  stage: deploy
  tags:
    - windows

  dependencies:
    - build_job

  variables:
    GIT_STRATEGY: none   # ❌ Don't use GitLab repo

  script:
    - echo "🚀 Deploying latest GitHub code"

    # Server check
    - powershell -Command "hostname"

    # Clean old files
    - powershell -Command "Remove-Item 'D:\\test\\output\\*' -Recurse -Force -ErrorAction SilentlyContinue"

    # Copy new files
    - powershell -Command "Copy-Item * -Destination 'D:\\test\\output' -Recurse -Force"

    # Verify deployed file
    - powershell -Command "Write-Host '📄 Latest app.py:'"
    - powershell -Command "Get-Content 'D:\\test\\output\\app.py'"
